#!/bin/bash

echo "Starting sugar install..."

# Use the conf as the install guide
for var in `grep -iP "^(a|c|f|inst)" ./sugar`
do
  echo "Attempting to eval $var"
  eval $var
done

echo "Installing to $INSTDIR"
mkdir $INSTDIR
cp -R ./sugard/* $INSTDIR
cp ./sugar $INSTDIR
mv $CDIR/default $CDEF
mv $FDIR/default $FDEF
mv $FDIR/teardown $FREM

grep -P "sugar" ~/.bash_profile
if [[ ! !? == 0 ]]
then
  echo "echo 'Sourcing sugar...'" >> ~/.bash_profile
  echo ". $INSTDIR/sugar" >> ~/.bash_profile
fi

echo "Done"
